# HomeNetMon Horizontal Pod Autoscaler Configuration
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: homenetmon-hpa
  namespace: homenetmon
  labels:
    app.kubernetes.io/name: homenetmon
    app.kubernetes.io/component: autoscaler
    app.kubernetes.io/part-of: homenetmon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: homenetmon-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Custom metrics scaling based on request rate
  - type: Object
    object:
      metric:
        name: requests_per_second
      target:
        type: AverageValue
        averageValue: "100"
      describedObject:
        apiVersion: v1
        kind: Service
        name: homenetmon-service
  # Custom metrics scaling based on active connections
  - type: Object
    object:
      metric:
        name: active_connections
      target:
        type: AverageValue
        averageValue: "50"
      describedObject:
        apiVersion: v1
        kind: Service
        name: homenetmon-service
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max

---
# Worker Pod Autoscaler for Background Tasks
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: homenetmon-worker-hpa
  namespace: homenetmon
  labels:
    app.kubernetes.io/name: homenetmon
    app.kubernetes.io/component: worker-autoscaler
    app.kubernetes.io/part-of: homenetmon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: homenetmon-worker
  minReplicas: 1
  maxReplicas: 5
  metrics:
  # CPU-based scaling for workers
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  # Memory-based scaling for workers
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  # Custom metrics for queue depth
  - type: Object
    object:
      metric:
        name: queue_depth
      target:
        type: AverageValue
        averageValue: "10"
      describedObject:
        apiVersion: v1
        kind: Service
        name: redis-service
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 200
        periodSeconds: 60

---
# Monitoring Service Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: homenetmon-monitor-hpa
  namespace: homenetmon
  labels:
    app.kubernetes.io/name: homenetmon
    app.kubernetes.io/component: monitor-autoscaler
    app.kubernetes.io/part-of: homenetmon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: homenetmon-monitor
  minReplicas: 1
  maxReplicas: 3
  metrics:
  # CPU-based scaling for monitoring
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  # Memory-based scaling for monitoring
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
  # Custom metrics for devices monitored
  - type: Object
    object:
      metric:
        name: devices_monitored_count
      target:
        type: AverageValue
        averageValue: "100"
      describedObject:
        apiVersion: v1
        kind: Service
        name: homenetmon-service
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600  # 10 minutes - monitoring needs stability
      policies:
      - type: Pods
        value: 1
        periodSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60

---
# Vertical Pod Autoscaler for optimizing resource requests
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: homenetmon-vpa
  namespace: homenetmon
  labels:
    app.kubernetes.io/name: homenetmon
    app.kubernetes.io/component: vpa
    app.kubernetes.io/part-of: homenetmon
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: homenetmon-app
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: homenetmon
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 2
        memory: 4Gi
      controlledResources:
      - cpu
      - memory

---
# PodDisruptionBudget to ensure availability during scaling
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: homenetmon-pdb
  namespace: homenetmon
  labels:
    app.kubernetes.io/name: homenetmon
    app.kubernetes.io/component: pdb
    app.kubernetes.io/part-of: homenetmon
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: homenetmon
      app.kubernetes.io/component: app

---
# Custom Metrics API Configuration for application-specific metrics
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: homenetmon-metrics
  namespace: homenetmon
  labels:
    app.kubernetes.io/name: homenetmon
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: homenetmon
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: homenetmon
      app.kubernetes.io/component: app
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s