apiVersion: v1
kind: Service
metadata:
  name: {{ include "homenetmon.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homenetmon.labels" . | nindent 4 }}
    app.kubernetes.io/component: application
  annotations:
    {{- include "homenetmon.commonAnnotations" . | nindent 4 }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- if .Values.nginx.enabled }}
  - port: {{ .Values.service.port }}
    targetPort: 80
    protocol: TCP
    name: http
  {{- else }}
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  {{- end }}
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: app
  selector:
    {{- include "homenetmon.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: application

---
{{- if .Values.externalService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homenetmon.fullname" . }}-external
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homenetmon.labels" . | nindent 4 }}
    app.kubernetes.io/component: external
  annotations:
    {{- include "homenetmon.commonAnnotations" . | nindent 4 }}
    {{- with .Values.externalService.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.externalService.type }}
  ports:
  - port: {{ .Values.externalService.port }}
    {{- if .Values.nginx.enabled }}
    targetPort: 80
    {{- else }}
    targetPort: {{ .Values.service.targetPort }}
    {{- end }}
    protocol: TCP
    name: http
  selector:
    {{- include "homenetmon.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: application
{{- end }}

---
# Headless service for StatefulSet-like behavior if needed
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homenetmon.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homenetmon.labels" . | nindent 4 }}
    app.kubernetes.io/component: headless
  annotations:
    {{- include "homenetmon.commonAnnotations" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: app
  selector:
    {{- include "homenetmon.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: application