apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: homenetmon-hpa
  namespace: homenetmon
  labels:
    app.kubernetes.io/name: homenetmon
    app.kubernetes.io/component: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: homenetmon-app
  minReplicas: 3
  maxReplicas: 20
  metrics:
  # CPU utilization target
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory utilization target
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Custom metrics based on request rate
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: "100"
  # External metrics from load balancer
  - type: External
    external:
      metric:
        name: aws_alb_request_count_per_target
        selector:
          matchLabels:
            load_balancer: homenetmon-alb
      target:
        type: AverageValue
        averageValue: "30"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
      - type: Pods
        value: 4
        periodSeconds: 30
      selectPolicy: Max

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: homenetmon-redis-hpa
  namespace: homenetmon
  labels:
    app.kubernetes.io/name: homenetmon-redis
    app.kubernetes.io/component: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: homenetmon-redis
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Pods
        value: 1
        periodSeconds: 180
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: homenetmon-pdb
  namespace: homenetmon
  labels:
    app.kubernetes.io/name: homenetmon
    app.kubernetes.io/component: availability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: homenetmon
      app.kubernetes.io/component: application
  minAvailable: 2

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: homenetmon-redis-pdb
  namespace: homenetmon
  labels:
    app.kubernetes.io/name: homenetmon-redis
    app.kubernetes.io/component: availability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: homenetmon-redis
  minAvailable: 1